joint_settings:
  upper:
    name:
      - waist_y_joint
      - waist_p_joint
      - waist_r_joint
      - l_shoulder_p_joint
      - l_shoulder_r_joint
      - l_shoulder_y_joint
      - l_elbow_joint
      - l_wrist_y_joint
      - l_wrist_p_joint
      - l_wrist_r_joint
      - l_hand_y_joint
      - l_indexbase_joint #passive
      - l_indexmid_joint #passive
      - l_indexend_joint #passive
      - l_thumb_joint
      - neck_y_joint
      - neck_p_joint
      - neck_r_joint
      - r_shoulder_p_joint
      - r_shoulder_r_joint
      - r_shoulder_y_joint
      - r_elbow_joint
      - r_wrist_y_joint
      - r_wrist_p_joint
      - r_wrist_r_joint
      - r_hand_y_joint
      - r_indexbase_joint #passive
      - r_indexmid_joint #passive
      - r_indexend_joint #passive
      - r_thumb_joint
    aero_index: [15,25,10,18,19,20,21,22,23,24,27,-1,-1,-1,26,0,1,2,3,4,5,6,7,8,9,12,-1,-1,-1,11] #passive = -1
    ros_index: [21,20,19,11,12,13,14,15,16,17,27,-1,-1,-1,18,0,2,1,3,4,5,6,7,8,9,-1,-1,-1,-1,10] #passive = -1
    DOF: 24

  hand:
    right_number: 12  #11+1
    left_number: 27   #26+1

  lower:
    name:
      - knee_joint
      - ankle_joint
    aero_index: [1,0]
    ros_index: [1,0] # = [23,22] - upper DOF
    DOF: 2

  wheel:
    name:
      - wheels_body_to_front_left_mecanum_connector   #fixed, not used
      - wheels_body_to_front_right_mecanum_connector  #fixed, not used
      - wheels_body_to_rear_left_mecanum_connector    #fixed, not used
      - wheels_body_to_rear_right_mecanum_connector   #fixed, not used
    aero_index: [4,2,5,3]
    ros_index: [0,1,2,3]
