seed_r7_mover_controller:
  ros_rate: 0.05
  odom_rate: 0.02
  safety_rate: 0.5
  safety_duration: 1.0

  wheel_radius: 0.0762
  tread: 0.389518
  wheelbase: 0.482

  encoder_odom: false
  wheel_vel_limit: 9.0
  pub_robot_info: false
