# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  ankle_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  ankle_joint_mimic:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 1.2
    has_acceleration_limits: false
    max_acceleration: 0
  elbow_joint_mimic:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  elbow_middle_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  elbow_middle_joint_mimic:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  knee_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  knee_joint_mimic:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  r_indexbase_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  r_thumb_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder_p_joint:
    has_velocity_limits: true
    max_velocity: 0.6
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder_y_joint:
    has_velocity_limits: true
    max_velocity: 1.2
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_p_joint:
    has_velocity_limits: true
    max_velocity: 1.4
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_r_joint:
    has_velocity_limits: true
    max_velocity: 1.05
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_y_joint:
    has_velocity_limits: true
    max_velocity: 1.3
    has_acceleration_limits: false
    max_acceleration: 0