axis_linear:
  x: 1      #left axis up/down
  y: 0    #left axis left/right
scale_linear:
  x: 0.3
  y: 0.2
scale_linear_turbo:
  x: 0.6
  y: 0.4

axis_angular:
  yaw: 3      #right axis left/right
scale_angular:
  yaw: 0.6
scale_angular_turbo:
  yaw: 1.0

enable_button: 4       #L1 button
enable_turbo_button: 6  #L2 button
