use_map_topic: true
odom_model_type: "omni-corrected"
gui_publish_rate: 10.0
laser_max_beams: 60
laser_max_range: 10.0
min_particles: 300
max_particles: 800
kld_err: 0.05
kld_z: 0.99
odom_alpha1: 0.2
odom_alpha2: 0.4
odom_alpha3: 0.2
odom_alpha4: 0.4
odom_alpha5: 0.1
laser_z_hit: 0.5
laser_z_short: 0.05
laser_z_max: 0.05
laser_z_rand: 0.5
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_model_type: "beam"
laser_likelihood_max_dist: 2.0
update_min_d: 0.01
update_min_a: 0.01
resample_interval: 1

transform_tolerance: 1.0
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0

odom_frame_id: odom
base_frame_id: base_link