joint_settings:
  robot: typefcesy
  raw_data_size: 35
  body_data_size: 35
  base_data_size: 35

  upper:
    joints:
      - waist_y_joint
      - waist_p_joint
      - waist_r_joint
      - l_shoulder_p_joint
      - l_shoulder_r_joint
      - l_shoulder_y_joint
      - l_elbow_joint
      - l_wrist_y_joint
      - l_wrist_p_joint
      - l_wrist_r_joint
      - l_hand_y_joint
      - l_indexbase_joint 
      - l_indexmid_joint #passive
      - l_indexend_joint #passive
      - l_thumb_joint
      - neck_y_joint
      - neck_p_joint
      - neck_r_joint
      - r_shoulder_p_joint
      - r_shoulder_r_joint
      - r_shoulder_y_joint
      - r_elbow_joint
      - r_wrist_y_joint
      - r_wrist_p_joint
      - r_wrist_r_joint
      - r_hand_y_joint
      - r_indexbase_joint 
      - r_indexmid_joint #passive
      - r_indexend_joint #passive
      - r_thumb_joint
    aero_index: [15,25,10,18,19,20,21,22,23,24,27,28,-1,-1,26,0,1,2,3,4,5,6,7,8,9,12,13,-1,-1,11] #passive = -1

  hand:
    right_number: 12  #11+1
    left_number: 27   #26+1

  lower:
    joints:
      - knee_joint
      - ankle_joint
    aero_index: [1,0]

  wheel:
    joints:
      - wheels_body_to_front_left_mecanum_connector   #fixed, not used
      - wheels_body_to_front_right_mecanum_connector  #fixed, not used
      - wheels_body_to_rear_left_mecanum_connector    #fixed, not used
      - wheels_body_to_rear_right_mecanum_connector   #fixed, not used
    aero_index: [4,2,5,3]
